config:
  {%- if pillar.glance.server is defined %}
  {%- from "glance/map.jinja" import server with context %}
  glance-api.conf:
    source: "salt://glance/files/{{ server.version }}/glance-api.conf.{{ grains.os_family|default('Debian') }}"
    template: jinja
  glance-cache.conf:
    source: "salt://glance/files/{{ server.version }}/glance-cache.conf.{{ grains.os_family|default('Debian') }}"
    template: jinja
  glance-registry.conf:
    source: "salt://glance/files/{{ server.version }}/glance-registry.conf.{{ grains.os_family|default('Debian') }}"
    template: jinja
  glance-scrubber.conf:
    source: "salt://glance/files/{{ server.version }}/glance-scrubber.conf.{{ grains.os_family|default('Debian') }}"
    template: jinja
  glance-api-paste.ini:
    source: "salt://glance/files/{{ server.version }}/glance-api-paste.ini"
    template: jinja
  glance-registry-paste.ini:
    source: "salt://glance/files/{{ server.version }}/glance-registry-paste.ini"
    template: jinja
  policy.json:
    source: "salt://glance/files/{{ server.version }}/policy.json"
    template: jinja
  {%- endif %}